image: docker:latest

services:
 - docker:dind


stages:
 - build
 - test
 - release


variables:
 TEST_IMAGE: cikbzdevop.kbzbank.com.mm:8443/dtherhtun/helloworld:$CI_COMMIT_REF_NAME
 RELEASE_IMAGE: cikbzdevop.kbzbank.com.mm:8443/dtherhtun/helloworld:latest


before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN cikbzdevop.kbzbank.com.mm:8443


build:
 stage: build
 script:
  - docker build --pull -t $TEST_IMAGE .
  - docker push $TEST_IMAGE


test:
 stage: test
 script:
  - docker pull $TEST_IMAGE
  - docker run $TEST_IMAGE go test


release:
 stage: release
 script:
  - docker pull $TEST_IMAGE
  - docker tag $TEST_IMAGE $RELEASE_IMAGE
  - docker push $RELEASE_IMAGE
 only:
  - master

